- name: Ensure pre-requisite apt packages for docker repo are installed
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    
- name: Add Docker's gpg key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  state: present

- name: Add Docker's stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes
    
- name: Install docker package
  apt: pkg=docker-ce state=present
  
- name: Enable docker's user namespacing
  copy: src=files/daemon.json dest=/etc/docker/daemon.json
  when: enable_docker_namespaces|bool
  notify:
        - Restart docker
  
- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  
